#!/usr/bin/env bash
#9. To file, or not to file. Bash script that gives you information about the school file.

file="school"

if [ -e "$file" ]; then
	echo "school file exists"
	if [ -s "$file" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$file" ]; then
		echo "school is a regular file"
	else
		:
	fi
else
	echo "school file does not exists"
fi
