#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the requirements :-localhost resolves to 127.0.0.2 - facebook.com resolves to 8.8.8.8.

127.0.0.2 localhost
8.8.8.8 facebook.com

