#!/usr/bin/env bash
# A simplified version
pkill apache2
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
nginx -u nginx service nginx restart
