#!/usr/bin/env bash
# short script
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
